### ISSUE TITLE
libinput-gestures exists with python error: not enough values to unpack

### ISSUE THREAD

**Issue by amosbird** [bulletmark/libinput-gestures#326]
```
 ❯ libinput-gestures -l
libinput-gestures: session bspwm+x11 on Linux-5.10.79-1-lts-x86_64-with-glibc2.33, python 3.9.7, libinput 1.19.2
Hash: 7fdb535fddc8a8f2306c17ccf295e6b9
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       3 gesture swipe3left
swipe right      3 gesture swipe3right
swipe up         3 gesture swipe3up
swipe down       3 gesture swipe3down
swipe left       4 gesture swipe4left
swipe right      4 gesture swipe4right
swipe up         4 gesture swipe4up
swipe down       4 gesture swipe4down
pinch in           gesture pinch_in
pinch out          gesture pinch_out
pinch clockwise    gesture pinch_clockwise
pinch anticlockwise   gesture pinch_anticlockwise
device all
libinput-gestures: monitoring all devices
libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is not currently running.
libinput-gestures is set to autostart as a desktop application.
libinput-gestures is using custom configuration file.

```

**Describe the issue**

After running `libinput-gestures -v` for a while, it exists with the following error:

```
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
libinput-gestures: HOLD on 1 [0.0, 0.0]
Traceback (most recent call last):
  File "/usr/bin/libinput-gestures", line 833, in <module>
    main()
  File "/usr/bin/libinput-gestures", line 803, in main
    gesture, event = gevent[8:].split('_')
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by bulletmark** [comment]
Yes, thanks for your report. The code was perhaps too fragile to the libinput message format so commit 98b687e60ad128e7b4dc987860c5bab656ef79d1 fixes this, as [release 2.71](https://github.com/bulletmark/libinput-gestures/releases/tag/2.71).
