### ISSUE TITLE
libinput-gestures don't work

### ISSUE THREAD

**Issue by thymbahutymba** [bulletmark/libinput-gestures#67]
I have i problem to use this "function" i follow all wiki (i'm on Arch Linux) I install it from AUR, add user at groups (restart my pc) and start libinput-gestures-setup but i can't use gestures, it's don't work! Someone can help me pls!

andrea@HP-ProBook-4540s ~> libinput-gestures-setup stop
libinput-debug-events stopped.
libinput-gestures stopped.
andrea@HP-ProBook-4540s ~> libinput-gestures -d
libinput-gestures: using /home/andrea/.config/libinput-gestures.conf, session x11
libinput-gestures: device /dev/input/event10: SynPS/2 Synaptics TouchPad
libinput-gestures: configured with 6 gestures

i'm trying to swipe but it's don't work!

**Comment by bulletmark** [comment]
@thymbahutymba I added commit 860f78b25f9b9a7bbeb189a79977887877bf4ba2 in response to this issue. It adds a TROUBLESHOOTING section to the README. Please follow the steps there.

**Comment by thymbahutymba** [comment]
I'm trying all in your guide, i post output:
```
andrea@HP-ProBook-4540s ~> libinput-gestures -d
libinput-gestures: using /etc/libinput-gestures.conf, session x11
libinput-gestures: device /dev/input/event10: SynPS/2 Synaptics TouchPad
libinput-gestures: configured with 6 gestures
^CTraceback (most recent call last):
  File "/usr/bin/libinput-gestures", line 375, in <module>
    for line in cmd.stdout:
KeyboardInterrupt
andrea@HP-ProBook-4540s ~ [1]> libinput-gestures -r
-event10  DEVICE_ADDED     SynPS/2 Synaptics TouchPad        seat0 default group1  cap:p  size 89x50mm tap(dl off) left scroll-nat scroll-2fg-edge dwt-on
event10  POINTER_MOTION   +11.60s         0.00/-10.07
event10  POINTER_AXIS     +11.69s       vert -22.23* horiz 0.00 (finger)
event10  POINTER_AXIS     +11.72s       vert -26.53* horiz -12.29* (finger)
event10  POINTER_AXIS     +11.74s       vert -11.40* horiz -0.86* (finger)
event10  POINTER_AXIS     +11.77s       vert -43.34* horiz -17.14* (finger)
event10  POINTER_AXIS     +11.80s       vert -19.80* horiz -14.57* (finger)
event10  POINTER_AXIS     +11.83s       vert -7.47* horiz -6.86* (finger)
event10  POINTER_AXIS     +11.86s       vert -10.27* horiz -0.86* (finger)
event10  POINTER_AXIS     +11.89s       vert -6.16* horiz 0.00 (finger)
event10  POINTER_AXIS     +11.93s       vert 0.00* horiz 0.00* (finger)
event10  POINTER_AXIS     +16.51s       vert 0.00 horiz 11.14* (finger)
event10  POINTER_AXIS     +16.53s       vert -1.68* horiz 30.86* (finger)
event10  POINTER_AXIS     +16.56s       vert 0.00 horiz 19.43* (finger)
event10  POINTER_AXIS     +16.59s       vert 0.00 horiz 12.57* (finger)
event10  POINTER_AXIS     +16.62s       vert 0.00 horiz 12.29* (finger)
event10  POINTER_AXIS     +16.65s       vert 0.00 horiz 33.43* (finger)
event10  POINTER_AXIS     +16.68s       vert 0.00 horiz 17.14* (finger)
event10  POINTER_AXIS     +16.70s       vert 0.00 horiz 12.57* (finger)
event10  POINTER_AXIS     +16.73s       vert 0.00 horiz 6.86* (finger)
event10  POINTER_AXIS     +16.76s       vert 0.00 horiz 0.57* (finger)
event10  POINTER_AXIS     +17.10s       vert 0.00* horiz 0.00* (finger)
event10  POINTER_AXIS     +18.88s       vert 0.00 horiz 17.14* (finger)
event10  POINTER_AXIS     +18.91s       vert -3.36* horiz 23.43* (finger)
event10  POINTER_AXIS     +18.94s       vert -1.87* horiz 2.00* (finger)
event10  POINTER_AXIS     +18.96s       vert -0.19* horiz 0.00 (finger)
event10  POINTER_AXIS     +19.02s       vert 0.00 horiz 1.14* (finger)
event10  POINTER_AXIS     +19.08s       vert -3.55* horiz 17.14* (finger)
event10  POINTER_AXIS     +19.11s       vert -0.75* horiz 4.57* (finger)
event10  POINTER_AXIS     +19.14s       vert -1.12* horiz 1.43* (finger)
event10  POINTER_AXIS     +19.27s       vert -0.93* horiz 0.00 (finger)
event10  POINTER_AXIS     +19.30s       vert 0.00 horiz -0.57* (finger)
event10  POINTER_AXIS     +19.33s       vert -5.23* horiz -17.71* (finger)
event10  POINTER_AXIS     +19.36s       vert -15.13* horiz -45.43* (finger)
event10  POINTER_AXIS     +19.39s       vert -11.96* horiz -13.71* (finger)
event10  POINTER_AXIS     +19.41s       vert -7.10* horiz -6.57* (finger)
event10  POINTER_AXIS     +19.44s       vert -6.54* horiz -3.14* (finger)
event10  POINTER_AXIS     +19.52s       vert 0.00* horiz 0.00* (finger)
event10  POINTER_MOTION   +20.24s       -21.43/ 18.87
event10  POINTER_MOTION   +20.25s       -20.86/ 11.58
event10  POINTER_MOTION   +20.27s       -16.57/ 20.36
event10  POINTER_MOTION   +20.28s       -14.86/ 26.15
event10  POINTER_MOTION   +20.29s       -20.86/ 16.63
event10  POINTER_MOTION   +20.30s       -30.00/ 23.54
event10  POINTER_MOTION   +20.32s       -17.71/ 37.55
event10  POINTER_MOTION   +20.33s       -31.45/ 74.37
event10  POINTER_MOTION   +20.34s       -20.31/ 27.64
event10  POINTER_MOTION   +20.36s       -15.43/ 19.99
event10  POINTER_MOTION   +20.37s       -11.43/ 30.64
event10  POINTER_MOTION   +20.38s        -6.00/ 16.07
event10  POINTER_MOTION   +20.40s        -3.71/  8.03
event10  POINTER_MOTION   +20.41s        -3.14/  5.42
event10  POINTER_MOTION   +20.42s        -2.57/  4.30
event10  POINTER_MOTION   +20.44s        -1.71/  0.00
event10  POINTER_AXIS     +21.20s       vert -18.31* horiz 0.29* (finger)
event10  POINTER_AXIS     +21.23s       vert -22.42* horiz 12.57* (finger)
event10  POINTER_AXIS     +21.25s       vert -14.20* horiz 6.86* (finger)
event10  POINTER_AXIS     +21.28s       vert -11.96* horiz 4.57* (finger)
event10  POINTER_AXIS     +21.31s       vert -10.46* horiz 5.71* (finger)
event10  POINTER_AXIS     +21.34s       vert -21.48* horiz 12.00* (finger)
event10  POINTER_AXIS     +21.36s       vert 0.00* horiz 0.00* (finger)
^CTraceback (most recent call last):
  File "/usr/bin/libinput-gestures", line 375, in <module>
    for line in cmd.stdout:
KeyboardInterrupt
```

**Comment by bulletmark** [comment]
Can you please paste the full output of `libinput-list-devices` here.

**Comment by bulletmark** [comment]
Unfortunately your touchpad does not report GESTURE events. There have been a number of people here who have reported the same or similar problem. E.g. see issues #12, #16, #39, #47, #62.

With commit c16a8e8d4e6dc2ad7bb5211dc83734df1915c254 I added a note to the TROUBLESHOOTING section in the README about your situation.

**Comment by thymbahutymba** [comment]
I look that my touchpad support 3-fringer according to archwiki: [https://wiki.archlinux.org/index.php/Touchpad_Synaptics_(Italiano)#Usare_xinput_per_determinare_le_funzionalit.C3.A0_del_touchpad] i post my output:
```andrea@HP-ProBook-4540s ~> xinput list-props "SynPS/2 Synaptics TouchPad" | grep Capabilities
	Synaptics Capabilities (331):	1, 0, 1, 1, 1, 1, 1
```
My touchpad hasn't got only central button. How i can fix this problem?
